#include "orchestrator/orchestrator.h"

#include <iostream>
#include <ostream>

#include "compiler_stage/compiler_stage.h"
#include <stdexcept>
#include <string>
#include <set>

#include "errors/valuascript_exception.h"
#include "stages/file_reader/file_reader_stage.h"
#include "stages/lexer/lexer_stage.h"

namespace valuascript::compiler {
    void Orchestrator::validate_stages_pipeline() const {
        std::set<CompilerStageArtifactCode> available_artifacts = {CompilerStageArtifactCode::FilePath};

        for (const auto &stage: stages_pipeline_) {
            for (const auto &dependency: stage->get_dependencies()) {
                if (!available_artifacts.contains(dependency)) {
                    std::string error_msg = "Invalid Compiler Pipeline Configuration:\n";
                    error_msg += "Stage '" + stage->get_name() + "' requires Artifact Code '";
                    error_msg += std::to_string(static_cast<int>(dependency));
                    error_msg += "', but it has not been generated by any previous stage.";

                    throw std::logic_error(error_msg);
                }
            }

            available_artifacts.insert(stage->get_output_artifact());
        }
    }

    void Orchestrator::initialise_file_path(const std::string &file_path) {
        pipeline_artifacts_.clear();
        pipeline_artifacts_.emplace_back(CompilerStageArtifactCode::FilePath, file_path);
    };

    Orchestrator::Orchestrator() {
        stages_pipeline_.clear();

        add_stage(std::make_unique<FileReaderStage>());
        add_stage(std::make_unique<LexerStage>());

        validate_stages_pipeline();
    }

    void Orchestrator::run(const std::string &file_path) {
        try {
            initialise_file_path(file_path);

            for (const auto &stage: stages_pipeline_) {
                pipeline_artifacts_.push_back(stage->run(pipeline_artifacts_));
            }
        } catch (const ValuaScriptException &e) {
            std::cerr << "Compilation Error: " << e.what() << std::endl;
        } catch (const std::logic_error &e) {
            std::cerr << "INTERNAL COMPILER ERROR: " << e.what() << std::endl;
            std::cerr << "Please report this bug to the maintainers." << std::endl;
        }
    }
}
