#pragma once
#include <vector>
#include <memory>
#include <set>
#include "compiler_stage/compiler_stage.h"

using namespace valuascript;

namespace valuascript::compiler {
    inline void validate_stages_pipeline(const std::vector<std::unique_ptr<CompilerStage>> &stages) {
        std::set<CompilerStageArtifactCode> available_artifacts = {CompilerStageArtifactCode::FilePath};

        for (const auto &stage: stages) {
            for (const auto &dependency: stage->get_dependencies()) {
                if (!available_artifacts.contains(dependency)) {
                    std::string error_msg = "Invalid Compiler Pipeline Configuration:\n";
                    error_msg += "Stage '" + stage->get_name() + "' requires Artifact Code '";
                    error_msg += std::to_string(static_cast<int>(dependency));
                    error_msg += "', but it has not been generated by any previous stage.";

                    throw std::logic_error(error_msg);
                }
            }

            available_artifacts.insert(stage->get_output_artifact());
        }
    }

    class Orchestrator {
        std::vector<std::unique_ptr<CompilerStage> > stages_;
        std::vector<CompilerStageArtifact> artifacts_;

        void initialise_file_path(const std::string &file_path);

    public:
        Orchestrator();

        void add_stage(std::unique_ptr<CompilerStage> stage) {
            stages_.push_back(std::move(stage));
        }

        void run(const std::string &file_path);
    };
}
